# إعدادات JVM لعملية البناء
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# تفعيل البناء المتوازي والتخزين المؤقت لتسريع البناء
org.gradle.parallel=true
org.gradle.caching=true

# استخدام مكتبات AndroidX
android.useAndroidX=true

# ترميز Kotlin بطريقة أنماط الرسمية
kotlin.code.style=official

# عدم توليد ملفات R لكل مكتبة (تحسين الأداء)
android.nonTransitiveRClass=true
